name: Build Release APK

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ] # Trigger on PRs to main

jobs:
  build_release_apk:
    name: Build Release APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Decode Keystore from Secret
      - name: Decode Keystore
        env:
          SIGNING_JKS_FILE_BASE64: ${{ secrets.SIGNING_JKS_FILE_BASE64 }}
        run: |
          echo "Creating Keystore directory..."
          mkdir -p android/app
          echo "Decoding Keystore file..."
          echo "$SIGNING_JKS_FILE_BASE64" | base64 --decode > android/app/upload-keystore.jks
          echo "Keystore file created."
          ls -l android/app/ # Optional: Verify file exists

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.5' # Match pubspec.yaml
          channel: 'stable'
          cache: true
          
      # Install Dependencies
      - name: Install Flutter dependencies
        run: flutter pub get

      # Extract version from pubspec.yaml
      - name: Extract version
        id: extract_version
        run: |
          VERSION=$(grep ^version pubspec.yaml | sed -E 's/^version: //' | cut -d+ -f1)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Build only ARM & ARM64 APKs
      - name: Build Release APKs
        run: flutter build apk --release --target-platform android-arm,android-arm64 --split-per-abi
        env:
          # These secrets are used by Flutter build process via Gradle
          KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          # Explicitly point to the keystore file location might be needed depending on build.gradle setup
          # KEYSTORE_PATH: ${{ github.workspace }}/android/app/upload-keystore.jks 
          
      # Upload Release APK Artifacts
      - name: Upload Release APK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-apks-${{ env.VERSION }}
          path: |
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
